---
title: "Primer on Time Series Analysis"
subtitle: "Converse/Gardner Joint Lab Meeting"
output:
  html_document:
    fig_caption: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r set_options, echo=FALSE, cache=FALSE}
options(width = 100)
```

***

## Prepared by

[__Mark Scheuerell__](https://fish.uw.edu/faculty/mark-scheuerell/)  
_U.S. Geological Survey Washington Cooperative Fish and Wildlife Research Unit_  
_School of Aquatic and Fishery Sciences_  
_University of Washington_

<br>

## Topics

Links are included after each topic for both the knitted slide deck and the RMarkdown code used to generate them.

### Introduction to time series analysis

  * Characteristics, autocorrelation, cross-correlation | [slides](session_1/lec_01_intro.html) | [Rmd](session_1/lec_01_intro.Rmd)  
  
  * White noise, random walks and biased random walks | [slides](session_1/lec_02_WN_RW.html) | [Rmd](session_1/lec_02_WN_RW.Rmd)  
  
  * AR(_p_), MA(_q_), ARMA(_p_,_q_) models | [slides](session_1/lec_03_ARMA_models.html) | [Rmd](session_1/lec_03_ARMA_models.Rmd)  


### Introduction to state-space models

  * Univariate state-space models | [slides](session_2/lec_04_SSM.html) | [Rmd](session_2/lec_04_SSM.Rmd)   
  
  * Multivariate state-space models | [slides](session_2/lec_05_MSSM.html) | [Rmd](session_2/lec_05_MSSM.Rmd)  
  

### Additional state-space models

  * Regression with auto-correlated errors | [slides](session_3/lec_06_regr_ar1.html) | [Rmd](session_3/lec_06_regr_ar1.Rmd)
  
  * Dynamic Factor Analysis (DFA) | [slides](session_3/lec_07_DFA.html) | [Rmd](session_3/lec_07_DFA.Rmd)
  
  * Dynamic Linear Models (DLMs) | [slides](session_3/lec_08_DLM.html) | [Rmd](session_3/lec_08_DLM.Rmd)
  
***

<br>

## Additional information

Here is some additional information on the following topics:

### Background material

 * Backshift and Difference operators | [slides](additional/ts_operators.html) | [Rmd](docs/additional/ts_operators.Rmd)
 
 * Identifying stationary AR(_p_) models | [slides](additional/stationary_AR.html) | [Rmd](docs/additional/stationary_AR.Rmd)
 
 * Invertible MA(_q_) models | [slides](additional/invertible_MA.html) | [Rmd](docs/additional/invertible_MA.Rmd)
 
### Other resources

 * [FISH 550 - Applied Time Series Analysis](https://atsa-es.github.io/atsa/)

 * [Lab book with computer exercises](https://atsa-es.github.io/atsa-labs/)
 
 * The [__Stan__](https://mc-stan.org/) language for fitting Bayesian models 
 
 * The [__greta__](https://greta-stats.org/) language for fitting Bayesian models
 
 * [Fitting DFA models with __greta__](https://mdscheuerell.github.io/gretaDFA/)

 

